### ISSUE TITLE
meet some problems when training on flower102 dataset 

### ISSUE THREAD

**Issue by wnjxykkk** [BatsResearch/menghini-neurips23-code#1]
When I was training on flower102 dataset, it seemed did not train at all, the accuracy was only around 1 persent since it contains around 100 classes.

**Comment by CriMenghini** [comment]
Hi, thanks for reaching out!

Can you provide more details to let us reproduce the problem? For instance, which prompt modality are you tuning? What are your learning setting and training strategy?
