### ISSUE TITLE
docker as a testbed

### ISSUE THREAD

**Issue by pengbohua** [BatsResearch/menghini-neurips23-code#3]
Hi, thank you for your awesome code. Could you please provide a docker image to learn about the algorithm as the links to your exp data splits are dead.

**Comment by stephenbach** [comment]
Hi, thanks for reaching out about this. We don't have plans to make a docker image, but I noticed that some of the links in the README were dead because of a repo rename. I believe I've fixed them. Can you let me know if any other links are dead?
