### ISSUE TITLE
quesiton in TRZSL setting

### ISSUE THREAD

**Issue by jihwanp** [BatsResearch/menghini-neurips23-code#4]
Hi im new to this field and i have a minor question about TRZSL setting.
At first, I thought that in TRZSL, only images corresponding to unseen classes could be accessed during training. But after reading the paper in detail, pseudo labeling seems done for the unseen classes. Is my understanding correct?
Thanks

**Comment by stephenbach** [comment]
Yup, that's right. The "unseen" classes are pseudolabeled in this setting. They are unseen in the sense that we never have any labeled examples of them. The "transductive" part of the TRZSL name is what indicates this.
