### ISSUE TITLE
Balance Param Mistake

### ISSUE THREAD

**Issue by Noahwangyuchen** [BatsResearch/menghini-neurips23-code#5]
Thanks and appreciate your great work but there seems to be some mistakes in the code when computing self.balance_param. For instance, in the function 'update_training_set' of 'training_strategies.py' in SSL, self.balance_param = len(seen_imgs) /  len(unseen_imgs), which should be self.balance_param = len(unseen_imgs) / len(seen_imgs) I guess.

**Comment by CriMenghini** [comment]
Hi!

Thanks for the question!

The `training_strategies.py` file should be removed from the project as it belongs to an old code base. You can find the correct definition for the `self.balance` parameter for SSL, corresponding to your suggestion, in the following files:

- `methods/semi_supervised_learning/multimodal_fpl.py`
- `methods/semi_supervised_learning/textual_fpl.py`
- `methods/semi_supervised_learning/visual_fpl.py`

Hope this can help!

**Comment by CriMenghini** [comment]
The issue was referring to a file deprecated from the code base. We are now proceeding removing the file. Thank you!
