### ISSUE TITLE
Problems with program code training

### ISSUE THREAD

**Issue by cyoungx** [BatsResearch/menghini-neurips23-code#6]
Thank you for inspiring me with your outstanding work.

I ran into a problem regarding the training of the program code, I found that under `class TextualPrompt` in the unsupervised learning setting it seems that some of the code is related to the `TrainingStrategy`, and due to the lack of the `TrainingStrategy`, the program frequently reported errors after modifying the parameter passing problem, the type of the error was the lack of some kind of `AttributeError: 'TextualFPL' object has no attribute 'train'`. So I noticed that `methods/unsupervised_learning/training_strategies.py` has been deleted. May I ask if this code file and the reported error are related? If relevant, what are the contents?

Looking forward to your reply.

**Comment by cyoungx** [comment]
I see.

**Comment by Logictaosen007** [comment]
请问您解决了TrainingStrategy缺失的问题了吗
